package com.nidus.twinly.chat.domain;

public enum CommandErrorCode {

    INVALID_REQUEST,
    CLIENT_MSG_ID_CONFLICT,
    INVALID_MESSAGE_CURSOR,
    ROOM_NOT_FOUND,
    MATCH_NOT_FOUND,
    PARTICIPATION_NOT_FOUND,
    NOT_A_PARTICIPANT,
    NOT_ACTIVE_PARTICIPANT,
    ROOM_CLOSED,
    TEXT_SIZE_LIMIT_EXCEEDED,
    INTERNAL
}
