ALTER TABLE anon_session_persona_elements
    MODIFY dimension ENUM ('OPENNESS','CONSCIENTIOUSNESS','EXTRAVERSION','AGREEABLENESS','NEUROTICISM','LIFE_STYLE','CONFLICT_STYLE','COMMUNICATION_STYLE','INTEREST','DETAIL','SUMMARY') NOT NULL;

ALTER TABLE persona_elements
    MODIFY dimension ENUM ('OPENNESS','CONSCIENTIOUSNESS','EXTRAVERSION','AGREEABLENESS','NEUROTICISM','LIFE_STYLE','CONFLICT_STYLE','COMMUNICATION_STYLE','INTEREST','DETAIL','SUMMARY') NOT NULL;
