INSERT INTO organizations (name)
VALUES ('성균관대학교'),
       ('성신여자대학교'),
       ('고려대학교'),
       ('서울대학교'),
       ('연세대학교'),
       ('서강대학교'),
       ('한양대학교'),
       ('이화여자대학교'),
       ('중앙대학교'),
       ('경희대학교'),
       ('한국외국어대학교'),
       ('서울시립대학교'),
       ('건국대학교'),
       ('동국대학교'),
       ('홍익대학교'),
       ('숙명여자대학교'),
       ('서울과학기술대학교'),
       ('국민대학교'),
       ('숭실대학교'),
       ('세종대학교'),
       ('광운대학교'),
       ('명지대학교'),
       ('상명대학교'),
       ('가톨릭대학교'),
       ('서울여자대학교'),
       ('한성대학교'),
       ('서경대학교'),
       ('삼육대학교'),
       ('동덕여자대학교'),
       ('덕성여자대학교'),
       ('성공회대학교'),
       ('경기대학교'),
       ('강서대학교'),
       ('가야대학교'),
       ('가천대학교'),
       ('가톨릭관동대학교'),
       ('강남대학교'),
       ('강원대학교'),
       ('건양대학교'),
       ('경남대학교'),
       ('경북대학교'),
       ('경상국립대학교'),
       ('경인교육대학교'),
       ('계명대학교'),
       ('고신대학교'),
       ('공주교육대학교'),
       ('광주대학교'),
       ('광주과학기술원(GIST)'),
       ('국립경국대학교'),
       ('국립공주대학교'),
       ('국립군산대학교'),
       ('국립금오공과대학교'),
       ('국립목포대학교'),
       ('국립목포해양대학교'),
       ('국립부경대학교'),
       ('국립순천대학교'),
       ('국립창원대학교'),
       ('국립한국교통대학교'),
       ('국립한국해양대학교'),
       ('국립한밭대학교'),
       ('극동대학교'),
       ('나사렛대학교'),
       ('단국대학교'),
       ('대구대학교'),
       ('대구가톨릭대학교'),
       ('대구경북과학기술원(DGIST)'),
       ('대구교육대학교'),
       ('대구예술대학교'),
       ('대구한의대학교'),
       ('대진대학교'),
       ('동명대학교'),
       ('동서대학교'),
       ('동신대학교'),
       ('동아대학교'),
       ('동양대학교'),
       ('동의대학교'),
       ('목원대학교'),
       ('배재대학교'),
       ('백석대학교'),
       ('부산대학교'),
       ('부산가톨릭대학교'),
       ('부산교육대학교'),
       ('서울교육대학교'),
       ('서울기독대학교'),
       ('서울장신대학교'),
       ('서원대학교'),
       ('선문대학교'),
       ('성결대학교'),
       ('세명대학교'),
       ('송원대학교'),
       ('수원대학교'),
       ('순천향대학교'),
       ('신라대학교'),
       ('신한대학교'),
       ('아신대학교'),
       ('아주대학교'),
       ('안양대학교'),
       ('영남대학교'),
       ('영산대학교'),
       ('예수대학교'),
       ('예원예술대학교'),
       ('용인대학교'),
       ('우석대학교'),
       ('우송대학교'),
       ('울산대학교'),
       ('울산과학기술원(UNIST)'),
       ('원광대학교'),
       ('유원대학교'),
       ('을지대학교'),
       ('인제대학교'),
       ('인천대학교'),
       ('인천가톨릭대학교'),
       ('인하대학교'),
       ('장로회신학대학교'),
       ('전남대학교'),
       ('전북대학교'),
       ('전주대학교'),
       ('제주대학교'),
       ('제주국제대학교'),
       ('조선대학교'),
       ('중부대학교'),
       ('중원대학교'),
       ('진주교육대학교'),
       ('청운대학교'),
       ('청주대학교'),
       ('추계예술대학교'),
       ('춘천교육대학교'),
       ('충남대학교'),
       ('충북대학교'),
       ('칼빈대학교'),
       ('평택대학교'),
       ('포항공과대학교(POSTECH)'),
       ('한경국립대학교'),
       ('한국공학대학교'),
       ('한국과학기술원(KAIST)'),
       ('한국교원대학교'),
       ('한국기술교육대학교'),
       ('한국방송통신대학교'),
       ('한국성서대학교'),
       ('한국예술종합학교'),
       ('한국에너지공과대학교(KENTECH)'),
       ('한국전통문화대학교'),
       ('한국체육대학교'),
       ('한국침례신학대학교'),
       ('한국항공대학교'),
       ('한남대학교'),
       ('한동대학교'),
       ('한림대학교'),
       ('한서대학교'),
       ('한세대학교'),
       ('한신대학교'),
       ('한일장신대학교'),
       ('협성대학교'),
       ('호남신학대학교'),
       ('호서대학교'),
       ('가톨릭꽃동네대학교'),
       ('감리교신학대학교'),
       ('경운대학교'),
       ('경일대학교'),
       ('김천대학교'),
       ('남부대학교'),
       ('대전대학교'),
       ('부산외국어대학교'),
       ('부산장신대학교'),
       ('상지대학교'),
       ('서울신학대학교'),
       ('세한대학교'),
       ('영남신학대학교'),
       ('위덕대학교'),
       ('전주교육대학교'),
       ('차의과학대학교'),
       ('창신대학교'),
       ('청주교육대학교'),
       ('한라대학교'),
       ('호남대학교') AS new
ON DUPLICATE KEY UPDATE name = new.name;

INSERT INTO organization_domains (organization_id, domain)
VALUES ((SELECT id FROM organizations WHERE name = '성균관대학교'), 'skku.edu'),
       ((SELECT id FROM organizations WHERE name = '성균관대학교'), 'g.skku.edu'),
       ((SELECT id FROM organizations WHERE name = '성균관대학교'), 'o365.skku.edu'),
       ((SELECT id FROM organizations WHERE name = '성신여자대학교'), 'sungshin.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '성신여자대학교'), 'student.sungshin.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '고려대학교'), 'korea.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '서울대학교'), 'snu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '연세대학교'), 'yonsei.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '연세대학교'), 'o365.yonsei.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '서강대학교'), 'sogang.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '서강대학교'), 'u.sogang.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '서강대학교'), 'o365.sogang.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한양대학교'), 'hanyang.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '이화여자대학교'), 'ewha.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '이화여자대학교'), 'ewhain.net'),
       ((SELECT id FROM organizations WHERE name = '이화여자대학교'), 'i.ewha.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '중앙대학교'), 'cau.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '경희대학교'), 'khu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '경희대학교'), 'office.khu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한국외국어대학교'), 'hufs.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한국외국어대학교'), 'o365.hufs.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '서울시립대학교'), 'uos.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '서울시립대학교'), 'office.uos.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '건국대학교'), 'konkuk.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '건국대학교'), 'kku.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '동국대학교'), 'dgu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '동국대학교'), 'dongguk.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '동국대학교'), 'student.dongguk.edu'),
       ((SELECT id FROM organizations WHERE name = '홍익대학교'), 'g.hongik.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '홍익대학교'), 'mail.hongik.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '숙명여자대학교'), 'sookmyung.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '숙명여자대학교'), 'sm.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '서울과학기술대학교'), 'seoultech.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '서울과학기술대학교'), 'g.seoultech.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '국민대학교'), 'kookmin.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '국민대학교'), 'kookmin.kr'),
       ((SELECT id FROM organizations WHERE name = '숭실대학교'), 'soongsil.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '세종대학교'), 'sju.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '광운대학교'), 'kw.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '광운대학교'), 'office.kw.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '명지대학교'), 'mju.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '상명대학교'), 'sangmyung.kr'),
       ((SELECT id FROM organizations WHERE name = '상명대학교'), 'sangmyung.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '가톨릭대학교'), 'catholic.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '서울여자대학교'), 'swu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한성대학교'), 'hansung.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한성대학교'), 'hansung.edu'),
       ((SELECT id FROM organizations WHERE name = '서경대학교'), 'skuniv.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '삼육대학교'), 'syu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '삼육대학교'), 'syusw.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '삼육대학교'), 'syuin.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '동덕여자대학교'), 'dongduk.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '동덕여자대학교'), 'office.dongduk.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '덕성여자대학교'), 'duksung.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '성공회대학교'), 'office.skhu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '경기대학교'), 'kyonggi.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '경기대학교'), 'kgu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '강서대학교'), 'gangseo.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '가야대학교'), 'office.kaya.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '가천대학교'), 'gachon.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '가톨릭관동대학교'), 'cku.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '가톨릭관동대학교'), 'o365.cku.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '강남대학교'), 'kangnam.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '강원대학교'), 'kangwon.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '강원대학교'), 'ms365.kangwon.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '강원대학교'), 'ms365g.kangwon.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '강원대학교'), 'gwnu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '건양대학교'), 'konyang.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '경남대학교'), 'student.kyungnam.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '경북대학교'), 'knu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '경상국립대학교'), 'gnu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '경인교육대학교'), 'ginue.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '경인교육대학교'), 'office.ginue.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '계명대학교'), 'stu.kmu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '계명대학교'), 'kmu.kr'),
       ((SELECT id FROM organizations WHERE name = '고신대학교'), 'office.kosin.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '공주교육대학교'), 'gjue.kr'),
       ((SELECT id FROM organizations WHERE name = '광주대학교'), 'gwangju.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '광주과학기술원(GIST)'), 'gm.gist.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '광주과학기술원(GIST)'), 'gist.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '국립경국대학교'), 'student.gknu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '국립경국대학교'), 'student.anu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '국립공주대학교'), 'smail.kongju.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '국립군산대학교'), 'office365.kunsan.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '국립군산대학교'), 'kunsan.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '국립금오공과대학교'), 'kumoh.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '국립목포대학교'), 'mokpo.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '국립목포해양대학교'), 'stu.mmu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '국립부경대학교'), 'pukyong.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '국립순천대학교'), 's.scnu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '국립창원대학교'), 'gs.cwnu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '국립한국교통대학교'), 'ut.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '국립한국해양대학교'), 'g.kmou.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '국립한밭대학교'), 'edu.hanbat.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '국립한밭대학교'), 'o365.hanbat.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '극동대학교'), 'kdu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '나사렛대학교'), 'office.kornu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '단국대학교'), 'dankook.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '대구대학교'), 'daegu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '대구가톨릭대학교'), 'cu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '대구경북과학기술원(DGIST)'), 'dgist.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '대구교육대학교'), 'm365.dnue.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '대구예술대학교'), 'dgau.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '대구한의대학교'), 'dhu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '대진대학교'), 'daejin.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '대진대학교'), 'office.daejin.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '동명대학교'), 'g.tu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '동명대학교'), 'o365.tu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '동서대학교'), 'office.dongseo.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '동신대학교'), 'dsu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '동아대학교'), 'donga.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '동양대학교'), 'dyu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '동의대학교'), 'g.deu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '동의대학교'), 'office.deu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '목원대학교'), 'mokwon.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '배재대학교'), 'pcu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '백석대학교'), 'bu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '부산대학교'), 'pusan.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '부산가톨릭대학교'), 'student.cup.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '부산교육대학교'), 'student.bnue.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '서울교육대학교'), 'o365.snue.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '서울기독대학교'), 'scui.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '서울장신대학교'), 'office.sjs.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '서원대학교'), 'office.seowon.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '선문대학교'), 'sunmoon.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '성결대학교'), 'sungkyul.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '성결대학교'), 'office.sungkyul.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '세명대학교'), 'semyung.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '송원대학교'), 'office.songwon.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '수원대학교'), 'suwon.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '수원대학교'), 'office.suwon.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '순천향대학교'), 'sch.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '신라대학교'), 'sillain.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '신한대학교'), 'o.shinhan.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '아신대학교'), 'acts.university'),
       ((SELECT id FROM organizations WHERE name = '아주대학교'), 'ajou.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '안양대학교'), 'gs.anyang.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '영남대학교'), 'yu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '영남대학교'), 'ynu.kr'),
       ((SELECT id FROM organizations WHERE name = '영산대학교'), 'office.ysu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '예수대학교'), 'jsu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '예원예술대학교'), 'office.yewon.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '용인대학교'), 'yiu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '우석대학교'), 'g.woosuk.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '우석대학교'), 'stu.woosuk.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '우송대학교'), 'live.wsu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '울산대학교'), 'mail.ulsan.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '울산과학기술원(UNIST)'), 'unist.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '원광대학교'), 'wku.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '유원대학교'), 'stu.yd.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '을지대학교'), 'g.eulji.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '인제대학교'), 'oasis.inje.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '인제대학교'), 'live.inje.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '인천대학교'), 'inu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '인천가톨릭대학교'), 'm365.iccu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '인하대학교'), 'inha.edu'),
       ((SELECT id FROM organizations WHERE name = '장로회신학대학교'), 'puts.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '전남대학교'), 'jnu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '전북대학교'), 'jbnu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '전주대학교'), 'jj.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '제주대학교'), 'stu.jejunu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '제주국제대학교'), 'jeju.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '조선대학교'), 'chosun.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '조선대학교'), 'chosun.kr'),
       ((SELECT id FROM organizations WHERE name = '중부대학교'), 'jmail.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '중원대학교'), 'office.jwu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '중원대학교'), 'jwu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '진주교육대학교'), 'stu.cue.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '청운대학교'), 'chungwoon.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '청주대학교'), 'cju.kr'),
       ((SELECT id FROM organizations WHERE name = '청주대학교'), 'cju.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '청주대학교'), 'chongju.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '청주대학교'), 'cheongju.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '추계예술대학교'), 'o365.chugye.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '춘천교육대학교'), 'student.cnue.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '충남대학교'), 'o.cnu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '충남대학교'), 'g.cnu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '충북대학교'), 'chungbuk.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '칼빈대학교'), 'calvin.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '평택대학교'), 'ptu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '포항공과대학교(POSTECH)'), 'postech.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '포항공과대학교(POSTECH)'), 'g.postech.edu'),
       ((SELECT id FROM organizations WHERE name = '한경국립대학교'), 'hknu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한국공학대학교'), 'tukorea.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한국과학기술원(KAIST)'), 'kaist.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한국교원대학교'), 'knue.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한국기술교육대학교'), 'koreatech.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한국방송통신대학교'), 'knou.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한국성서대학교'), 'bible.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한국예술종합학교'), 'karts.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한국에너지공과대학교(KENTECH)'), 'kentech.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한국전통문화대학교'), 'knuh.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한국체육대학교'), 'm365.knsu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한국침례신학대학교'), 'stu.kbtus.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한국항공대학교'), 'kau.kr'),
       ((SELECT id FROM organizations WHERE name = '한남대학교'), 'gm.hannam.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한남대학교'), 'm365.hnu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한동대학교'), 'handong.edu'),
       ((SELECT id FROM organizations WHERE name = '한림대학교'), 'hallym.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한서대학교'), 'office.hanseo.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한세대학교'), 'hansei.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한신대학교'), 'hs.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한일장신대학교'), 'student.hanil.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '협성대학교'), 'office.uhs.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '호남신학대학교'), 'g.htus.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '호서대학교'), 'vision.hoseo.edu'),
       ((SELECT id FROM organizations WHERE name = '가톨릭꽃동네대학교'), 'office.kkot.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '감리교신학대학교'), 'mtu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '경운대학교'), 'ikw.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '경일대학교'), 'kiu.kr'),
       ((SELECT id FROM organizations WHERE name = '김천대학교'), 'gcu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '남부대학교'), 's.nambu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '대전대학교'), 'edu.dju.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '대전대학교'), 'o365.dju.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '부산외국어대학교'), 'office.bufs.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '부산장신대학교'), 'bpu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '상지대학교'), 'sj.sangji.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '서울신학대학교'), 'stu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '세한대학교'), 'office.sehan.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '영남신학대학교'), 'ytus.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '위덕대학교'), 'uu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '전주교육대학교'), '365.jnue.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '차의과학대학교'), 'chauniv.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '차의과학대학교'), 'student.cha.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '창신대학교'), 'office.cs.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '청주교육대학교'), 'office.cje.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한라대학교'), 'halla.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '호남대학교'), 'honam.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '호남대학교'), 'my.honam.ac.kr') AS new
ON DUPLICATE KEY UPDATE organization_id = new.organization_id;
