INSERT INTO organizations (name)
VALUES ('성균관대학교'),
       ('성신여자대학교'),
       ('고려대학교'),
       ('서울대학교'),
       ('연세대학교'),
       ('서강대학교'),
       ('한양대학교'),
       ('이화여자대학교'),
       ('중앙대학교'),
       ('경희대학교'),
       ('한국외국어대학교'),
       ('서울시립대학교'),
       ('건국대학교'),
       ('동국대학교'),
       ('홍익대학교'),
       ('숙명여자대학교'),
       ('서울과학기술대학교'),
       ('국민대학교'),
       ('숭실대학교'),
       ('세종대학교'),
       ('광운대학교'),
       ('명지대학교'),
       ('상명대학교'),
       ('가톨릭대학교'),
       ('서울여자대학교'),
       ('한성대학교'),
       ('서경대학교'),
       ('삼육대학교'),
       ('동덕여자대학교'),
       ('덕성여자대학교'),
       ('성공회대학교'),
       ('경기대학교'),
       ('강서대학교') AS new
ON DUPLICATE KEY UPDATE name = new.name;

INSERT INTO organization_domains (organization_id, domain)
VALUES ((SELECT id FROM organizations WHERE name = '성균관대학교'), 'skku.edu'),
       ((SELECT id FROM organizations WHERE name = '성균관대학교'), 'g.skku.edu'),
       ((SELECT id FROM organizations WHERE name = '성신여자대학교'), 'sungshin.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '고려대학교'), 'korea.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '서울대학교'), 'snu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '연세대학교'), 'yonsei.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '연세대학교'), 'o365.yonsei.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '서강대학교'), 'sogang.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '서강대학교'), 'u.sogang.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '서강대학교'), 'o365.sogang.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한양대학교'), 'hanyang.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '이화여자대학교'), 'ewha.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '이화여자대학교'), 'ewhain.net'),
       ((SELECT id FROM organizations WHERE name = '이화여자대학교'), 'i.ewha.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '중앙대학교'), 'cau.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '경희대학교'), 'khu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한국외국어대학교'), 'hufs.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한국외국어대학교'), 'o365.hufs.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '서울시립대학교'), 'uos.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '서울시립대학교'), 'office.uos.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '건국대학교'), 'konkuk.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '건국대학교'), 'kku.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '동국대학교'), 'dgu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '동국대학교'), 'dongguk.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '홍익대학교'), 'g.hongik.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '홍익대학교'), 'mail.hongik.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '숙명여자대학교'), 'sookmyung.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '서울과학기술대학교'), 'seoultech.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '서울과학기술대학교'), 'g.seoultech.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '국민대학교'), 'kookmin.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '국민대학교'), 'kookmin.kr'),
       ((SELECT id FROM organizations WHERE name = '숭실대학교'), 'soongsil.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '세종대학교'), 'sju.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '광운대학교'), 'kw.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '광운대학교'), 'office.kw.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '명지대학교'), 'mju.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '상명대학교'), 'sangmyung.kr'),
       ((SELECT id FROM organizations WHERE name = '상명대학교'), 'sangmyung.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '가톨릭대학교'), 'catholic.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '서울여자대학교'), 'swu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한성대학교'), 'hansung.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '한성대학교'), 'hansung.edu'),
       ((SELECT id FROM organizations WHERE name = '서경대학교'), 'skuniv.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '삼육대학교'), 'syu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '삼육대학교'), 'syusw.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '동덕여자대학교'), 'dongduk.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '덕성여자대학교'), 'duksung.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '성공회대학교'), 'office.skhu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '경기대학교'), 'kyonggi.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '경기대학교'), 'kgu.ac.kr'),
       ((SELECT id FROM organizations WHERE name = '강서대학교'), 'gangseo.ac.kr') AS new
ON DUPLICATE KEY UPDATE organization_id = new.organization_id;
