spring:
  config:
    import: optional:file:../.env[.properties]
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:db/migration, classpath:db/seed

logging:
  file:
    name: logs/app.log

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

springwolf:
  enabled: true

portone:
  allowed-channel-types: LIVE,TEST

revenue-cat:
  environment: SANDBOX
