spring:
  flyway:
    locations: classpath:db/migration, classpath:db/stage
    out-of-order: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.nidus.twinly: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

springwolf:
  enabled: true
  docket:
    servers:
      stomp:
        host: ${WS_HOST}/ws/v1/
